"""
6_Documentation.py
Reference documentation for the 3D Mold Making workflow.
"""

import streamlit as st
from i18n import render_app_sidebar, t as tr

st.set_page_config(page_title=tr("page.documentation.title", "Documentation"), layout="wide")
render_app_sidebar()
st.title(tr("page.documentation.title", "Documentation"))
st.caption(tr("page.documentation.caption", "Reference materials, material specs, and workflow notes for the 3D mold making process."))

# ─────────────────────────────────────────
# Materials
# ─────────────────────────────────────────
st.header(tr("page.documentation.materials", "Materials"))

with st.expander("Accu-Cast Alginate 570 PGV", expanded=False):
    st.markdown("""
**Manufacturer:**

**Product:**

**Mix Ratio:**

**Working Time:**

**Set Time:**

**Notes:**
""")

with st.expander("Dry Investment / Plaster + Silica", expanded=False):
    st.markdown("""
**Manufacturer:**

**Product:**

**Mix Ratio (Plaster : Silica):**

**Water Ratio:**

**Working Time:**

**Set Time:**

**Notes:**
""")

with st.expander("R&R 910 Investment", expanded=False):
    st.markdown("""
**Manufacturer:**

**Product:**

**Mix Ratio (× 1.88):**

**Water Ratio:**

**Working Time:**

**Set Time:**

**Notes:**
""")

with st.expander("Siratech Silicone", expanded=False):
    st.markdown("""
**Manufacturer:**

**Product:**

**Mix Ratio (Part A : Part B):**

**Density (g/cm³):**

**Working Time:**

**Cure Time:**

**Compatible With:**

**Notes:**
""")

st.divider()

# ─────────────────────────────────────────
# Workflows
# ─────────────────────────────────────────
st.header(tr("page.documentation.workflows", "Workflows"))

with st.expander("Alginate Mold — Step by Step", expanded=False):
    st.markdown("""
**Preparation**

**Mixing**

**Pouring**

**Demolding**

**Notes:**
""")

with st.expander("Investment Mold — Step by Step", expanded=False):
    st.markdown("""
**Preparation**

**Mixing**

**Pouring**

**Firing**

**Notes:**
""")

with st.expander("Silicone Mold — Step by Step", expanded=False):
    st.markdown("""
**Preparation**

**Mixing**

**Pouring**

**Cure**

**Demolding**

**Notes:**
""")

st.divider()

# ─────────────────────────────────────────
# Tools & Output
# ─────────────────────────────────────────
st.header(tr("page.documentation.tools_output", "Tools & Output"))

with st.expander("What The STL Files Are Used For", expanded=False):
    st.markdown("""
The `.stl` files generated by this app are typically **tooling files**, not final artwork.

In this workflow, a printed part is usually used to:

- create an alginate negative
- create a silicone negative
- form a positive or support part used during mold making
- generate a plaster / silica or investment mold for kiln casting

In most cases, the printed part is an **intermediate fabrication tool**. The glass does not usually touch the printed plastic or resin directly in the final firing process.
""")

with st.expander("FDM Printing", expanded=False):
    st.markdown("""
**Typical Use**

- larger vessel molds
- support plugs
- quick draft models
- parts where strength matters more than very fine surface detail

**Notes**

- FDM is usually the more practical choice for larger mold forms
- layer lines may print through into alginate or silicone unless the model is sealed or smoothed
- wall strength, infill, and print orientation matter when the printed part will be used as a casting tool
- a larger nozzle or thicker layer height may be acceptable for studio tooling, depending on the relief detail

**Good Fit**

Use FDM when the model is structural, large, or intended mainly to support a mold-making step rather than capture very fine surface detail.
""")

with st.expander("Resin Printing", expanded=False):
    st.markdown("""
**Typical Use**

- cameo molds
- fine relief studies
- small, highly detailed prototypes
- surfaces where crisp detail matters more than print speed or size

**Notes**

- resin usually gives cleaner detail and a smoother surface than FDM
- printed resin parts must be washed and fully cured before use
- some resins are brittle, so handling and demolding need care
- resin printing is often better for detail capture, but less convenient for larger vessel-scale tooling

**Good Fit**

Use resin when the surface quality of the printed master is important and the model size stays within a practical resin print volume.
""")

with st.expander("Glass, Kiln, And Mold Workflow", expanded=False):
    st.markdown("""
**Typical Sequence**

1. Generate the `.stl` file in the app.
2. Print the model in FDM or resin.
3. Use the printed part to create an alginate, silicone, or other intermediate mold.
4. Build the final refractory mold in plaster / silica, investment, or a related casting system.
5. Fire the glass in the kiln using the refractory mold.

**Important Distinction**

The printer and the kiln are part of the same fabrication chain, but they do different jobs:

- the **printer** makes the tooling or master form
- the **mold materials** create the glass-safe refractory form
- the **kiln** processes the glass in the final mold

This is why print quality, mold design, and firing strategy all affect the finished glass, even though the printed part is usually removed earlier in the process.
""")

with st.expander("Studio Toolchain Notes", expanded=False):
    st.markdown("""
Common tools in this workflow may include:

- image editing software for artwork preparation
- the modeling pages in this app for STL generation
- an FDM or resin printer for tooling
- alginate, silicone, plaster / silica, grog, fiberglass, or investment materials
- a glass kiln for casting, firing, and annealing

Each tool affects the next stage, so it is useful to think of the STL as the **start of the mold workflow**, not the end of the design process.
""")

st.divider()

# ─────────────────────────────────────────
# Glossary
# ─────────────────────────────────────────
st.header(tr("page.documentation.glossary", "Glossary"))

with st.expander("Terms & Definitions", expanded=False):
    st.markdown("""
| Term | Definition |
|------|-----------|
| **Max Z** | |
| **Base (Zb)** | |
| **Relief (Za)** | |
| **STL Volume** | |
| **Art Space Volume** | |
| **Actual Art Volume** | |
| **Vol to Max Z** | |
| **Gap Width** | |
| **Adjust Base Z (Zi)** | |
| **Mold Volume** | |
""")

st.divider()

# ─────────────────────────────────────────
# Safety & Handling
# ─────────────────────────────────────────
st.header(tr("page.documentation.safety", "Safety & Handling"))

with st.expander("Alginate", expanded=False):
    st.markdown("_Placeholder — add safety and handling notes here._")

with st.expander("Investment / Plaster + Silica", expanded=False):
    st.markdown("_Placeholder — add safety and handling notes here._")

with st.expander("Silicone", expanded=False):
    st.markdown("_Placeholder — add safety and handling notes here._")

st.divider()

# ─────────────────────────────────────────
# Notes
# ─────────────────────────────────────────
st.header(tr("page.documentation.general_notes", "General Notes"))
st.markdown("_Placeholder — add general workflow notes, tips, and observations here._")
